databases:
  - name: mysitedb
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: django-asset-manager
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
